import Link from "next/link";
import { SiteHeader, SiteFooter } from "@/components/SiteChrome";

const facts = [
  { value: "9.2 M", label: "personas vivían en CDMX en 2020", source: "INEGI · Censo 2020", href: "https://www.inegi.org.mx/app/saladeprensa/noticia.html?id=6288" },
  { value: "24/7", label: "el 911 de CDMX atiende urgencias médicas", source: "C5 Ciudad de México", href: "https://datos.cdmx.gob.mx/dataset/llamadas-numero-de-atencion-a-emergencias-911" },
  { value: "88.6 M", label: "personas de 60+ en LATAM y el Caribe en 2022", source: "CEPAL · 2022", href: "https://www.cepal.org/es/enfoques/panorama-envejecimiento-tendencias-demograficas-america-latina-caribe" },
];

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero shell"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> PILOTO EN CIUDAD DE MÉXICO</p><h1>Más cerca cuando alguien <em>necesita ayuda.</em></h1><p className="hero-lead">Un botón en casa y una red familiar que puede enterarse, confirmar quién responde y acompañar el día a día.</p><p className="hero-motto">Tu red de apoyo en dos toques.</p><div className="hero-actions"><Link className="button button-primary" href="/demo">Ver demostración <span aria-hidden="true">↗</span></Link><a className="button button-quiet" href="#como-funciona">Cómo funciona <span aria-hidden="true">↓</span></a></div><p className="microcopy">Demostración simulada. No envía alertas ni llama a emergencias.</p></div><div className="hero-visual" role="img" aria-label="Representación del botón en casa y un familiar que confirma"><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><div className="device-illustration"><div className="device-led" /><div className="device-button">P</div><p>Pulso en casa</p></div><div className="status-card"><div className="status-card-top"><span className="status-icon">✦</span><span className="status-badge">RED FAMILIAR</span></div><strong>Alguien necesita apoyo</strong><p>Aviso a contactos elegidos</p><div className="status-divider" /><div className="avatar-row"><span className="avatar">M</span><div><b>María confirmó</b><small>La familia sabe quién responde</small></div><span className="checkmark">✓</span></div></div><span className="visual-caption">Representación del flujo propuesto</span></div></section>

    <section className="section section-tinted" id="como-funciona"><div className="shell"><div className="section-intro"><p className="eyebrow">UN FLUJO CLARO</p><h2>La tranquilidad empieza por saber <em>qué sigue.</em></h2><p>Una señal sencilla, una familia informada y una persona que asume la respuesta.</p></div><div className="steps-grid"><article className="step-card"><span className="step-num">01</span><span className="step-symbol">◎</span><h3>Presiona el botón</h3><p>La persona en casa mantiene presionado su botón Pulso. El prototipo físico ya detecta ese gesto.</p></article><article className="step-card"><span className="step-num">02</span><span className="step-symbol">↗</span><h3>La red se entera</h3><p>La versión objetivo avisará por correo a los familiares elegidos y verificados.</p></article><article className="step-card"><span className="step-num">03</span><span className="step-symbol">✓</span><h3>Alguien confirma</h3><p>Un familiar tomará la responsabilidad y el resto podrá ver el estado del incidente.</p></article></div><p className="section-note">Los pasos de aviso y confirmación aún están en desarrollo. <Link href="/demo">Explora el recorrido simulado →</Link></p></div></section>

    <section className="section shell" id="familias"><div className="split-section"><div><p className="eyebrow">HECHO PARA CUIDARNOS</p><h2>Una experiencia que entiende a <em>toda la familia.</em></h2><p className="section-lead">Pulso se diseña alrededor de las conversaciones que importan: pedir ayuda, saber quién responde y preguntar cómo estuvo el día.</p><Link href="/demo" className="text-link">Ver la experiencia ↗</Link></div><div className="benefit-list"><article><span className="benefit-icon">01</span><div><h3>Para quien está en casa</h3><p>Un gesto físico sencillo y una pantalla con texto grande, contraste y estados claros.</p></div></article><article><span className="benefit-icon">02</span><div><h3>Para familiares</h3><p>Un solo lugar para entender el aviso y saber quién se encargará de responder.</p></div></article><article><span className="benefit-icon">03</span><div><h3>Para personas cuidadoras</h3><p>Un chequeo voluntario para abrir conversaciones cotidianas, sin dar diagnósticos.</p></div></article></div></div></section>

    <section className="section facts-section" id="contexto"><div className="shell"><div className="section-intro"><p className="eyebrow">EL CONTEXTO IMPORTA</p><h2>Empezamos en CDMX.<br /><em>Pensamos en LATAM.</em></h2><p>Datos públicos para entender la escala; no son resultados ni usuarios de Pulso.</p></div><div className="facts-grid">{facts.map(f => <article className="fact-card" key={f.value}><strong>{f.value}</strong><p>{f.label}</p><a href={f.href} target="_blank" rel="noopener noreferrer">{f.source} ↗</a></article>)}</div></div></section>

    <section className="section shell" id="cuidado"><div className="care-panel"><div className="care-art" aria-hidden="true"><div className="care-circle"><span>♡</span><div className="care-line"><i /><i /><i /><i /><i /></div></div><span className="care-spark spark-a">✳</span><span className="care-spark spark-b">✳</span></div><div className="care-copy"><p className="eyebrow">MÁS ALLÁ DE UNA ALERTA</p><h2>Cuidar también es <em>preguntar cómo estás.</em></h2><p>El chequeo diario propuesto ayuda a registrar cómo se siente la persona y a conversar sobre cambios. Es voluntario y no reemplaza una valoración médica.</p><Link className="button button-outline" href="/chequeo">Conocer el chequeo ↗</Link></div></div></section>

    <section className="section trust-section" id="confianza"><div className="shell trust-grid"><div><p className="eyebrow">DISEÑADO CON RESPONSABILIDAD</p><h2>La confianza se construye con <em>límites claros.</em></h2></div><div><p>Pulso está en fase de prototipo. La demo no envía mensajes reales. No tenemos convenio con autoridades ni conexión automática al 911. En una urgencia, un familiar debe llamar al 911.</p><p>El diseño de Stellar contempla registrar solo una prueba de integridad del incidente, nunca información clínica, correo, domicilio o IP.</p><a className="text-link" href="https://github.com/arantxaamr/alerta-medica-esp32-stellar/blob/main/WHITEPAPER_PULSO.md">Leer el white paper ↗</a></div></div></section>

    <section className="closing shell"><p className="eyebrow">CONOCE PULSO</p><h2>Una red preparada empieza<br />con una <em>conversación.</em></h2><p>Explora la experiencia de una solicitud de ayuda y la confirmación familiar.</p><Link className="button button-light" href="/demo">Ver demostración ↗</Link><small>Simulación; no genera incidentes ni avisos reales.</small></section>
  </main><SiteFooter /></>;
}
