"use client";

import { useState } from "react";
import Link from "next/link";
import { SiteHeader, SiteFooter } from "@/components/SiteChrome";

type Step = 0 | 1 | 2;

export default function DemoPage() {
  const [step, setStep] = useState<Step>(0);
  return <><SiteHeader /><main className="inner-page"><div className="shell inner-shell"><Link href="/" className="back-link">← Volver a Pulso</Link><p className="eyebrow">DEMOSTRACIÓN INTERACTIVA</p><h1>Así se vería una red que <em>responde.</em></h1><p className="inner-lead">Sigue el recorrido de una solicitud de ayuda desde el botón hasta la confirmación familiar.</p><div className="notice" role="note"><strong>Es una simulación.</strong> Ningún botón de esta página crea incidentes reales, envía correos ni avisa al 911.</div><section className="demo-panel" aria-labelledby="demo-title"><p className="eyebrow">ESTADO {step + 1} DE 3</p><h2 id="demo-title">{step === 0 ? "Listos para empezar" : step === 1 ? "Solicitud registrada en la demo" : "María confirmó que atenderá"}</h2><p>{step === 0 ? "Imagina que Ana está en casa y necesita contactar a su red de apoyo." : step === 1 ? "En el producto futuro, sus contactos verificados recibirían un aviso. Aquí solo mostramos el flujo." : "En esta simulación, un familiar asumió la respuesta y la red puede verlo."}</p><div className="demo-state" aria-live="polite"><span aria-hidden="true">{step === 0 ? "◎" : step === 1 ? "↗" : "✓"}</span><div><strong>{step === 0 ? "Botón en casa, listo" : step === 1 ? "Esperando confirmación familiar" : "Familiar responsable: María"}</strong><small>{step === 0 ? "Presiona para simular el evento" : step === 1 ? "Todavía no se ha confirmado en este ejemplo" : "Estado final de la demostración"}</small></div></div><div className="demo-actions">{step === 0 && <button type="button" className="button button-danger" onClick={() => setStep(1)}>Simular pulsación del botón ↗</button>}{step === 1 && <button type="button" className="button button-primary" onClick={() => setStep(2)}>Simular confirmación familiar ✓</button>}{step > 0 && <button type="button" className="button button-outline" onClick={() => setStep(0)}>Reiniciar demo</button>}</div><p className="demo-disclaimer">No se enviaron avisos. Si estás ante una urgencia real en México, llama al <a href="tel:911">911</a>.</p></section><div className="page-actions"><Link className="button button-quiet" href="/chequeo">Conocer el chequeo diario ↗</Link><Link className="button button-quiet" href="/contactos">Ver red de contactos ↗</Link></div></div></main><SiteFooter /></>;
}
