import Link from "next/link";
import { redirect } from "next/navigation";
import { ContactForm } from "@/components/ContactForm";
import { LogoutButton } from "@/components/LogoutButton";
import { AppHeader } from "@/components/SiteChrome";
import { currentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { PollarShell } from "@/components/PollarShell";
import { InvitationActions } from "@/components/InvitationActions";

export default async function PanelPage() {
  const user = await currentUser();
  if (!user) redirect("/acceso");
  if (!user.profile?.consentAcceptedAt) redirect("/bienvenida");

  const isAdmin = user.role === "ADMIN";
  const isFamily = user.role === "FAMILY";
  const contacts = user.role === "USER" ? await prisma.contact.findMany({ where: { userId: user.id }, orderBy: { createdAt: "asc" } }) : [];
  const families = isFamily ? await prisma.contact.findMany({ where: { email: user.email }, include: { user: { include: { profile: true } } }, orderBy: { createdAt: "asc" } }) : [];
  const stats = isAdmin ? await Promise.all([prisma.user.count(), prisma.contact.count(), prisma.contact.count({ where: { verifiedAt: { not: null } } }), prisma.incident.count()]) : null;

  return <><AppHeader role={user.role} name={user.profile.displayName} /><main id="contenido" className="app-main"><div className="shell panel-shell"><div className="panel-top"><div><p className="eyebrow">{isAdmin ? "CENTRO DE OPERACIONES" : isFamily ? "TU RED DE CUIDADO" : "TU ESPACIO PULSO"}</p><h1>Hola, <em>{user.profile.displayName}.</em></h1><p className="inner-lead">{isAdmin ? "Vista general del piloto y su actividad operativa." : isFamily ? "Revisa tus invitaciones y acompaña a quienes decidieron contar contigo." : "Prepara tu red y revisa lo que falta antes de conectar tu botón."}</p></div><PollarShell apiKey={process.env.NEXT_PUBLIC_POLLAR_PUBLISHABLE_KEY}><LogoutButton /></PollarShell></div>
    <div className="pilot-banner"><span className="pilot-dot" /><div><strong>Piloto en configuración</strong><p>El acceso y los vínculos ya se guardan. Las alertas físicas se habilitarán al conectar la ESP32.</p></div><span className="status-pill pending">Modo simulación</span></div>
    {isAdmin && <><section className="panel-stats" aria-label="Resumen del piloto"><div><span>Cuentas</span><strong>{stats?.[0]}</strong><small>identidades verificadas</small></div><div><span>Contactos</span><strong>{stats?.[1]}</strong><small>invitaciones creadas</small></div><div><span>Vínculos</span><strong>{stats?.[2]}</strong><small>aceptados</small></div><div><span>Incidentes</span><strong>{stats?.[3]}</strong><small>registrados</small></div></section><div className="panel-grid"><section className="info-panel"><div className="panel-heading"><div><span className="panel-kicker">SALUD DEL SISTEMA</span><h2>Servicios del piloto</h2></div><span className="status-pill">Operativo</span></div><ul className="service-list"><li><span className="service-icon">P</span><div><strong>Pollar testnet</strong><small>Acceso por correo y cartera vinculada</small></div><b>Listo</b></li><li><span className="service-icon">DB</span><div><strong>Supabase</strong><small>Perfiles, sesiones e invitaciones</small></div><b>Listo</b></li><li><span className="service-icon muted">32</span><div><strong>ESP32 WROOM-32</strong><small>Conexión física pendiente</small></div><b className="pending-text">Siguiente etapa</b></li></ul></section><section className="info-panel"><span className="panel-kicker">PRIVACIDAD</span><h2>Vista limitada</h2><p>Este panel muestra actividad general. Las respuestas diarias de salud y datos personales no aparecen en esta vista.</p><Link className="text-link" href="/WHITEPAPER_PULSO.md">Ver criterios de datos →</Link></section></div></>}
    {isFamily && <div className="panel-grid family-grid"><section className="info-panel"><div className="panel-heading"><div><span className="panel-kicker">RED COMPARTIDA</span><h2>Invitaciones y vínculos</h2></div><span className="count-badge">{families.length}</span></div>{families.length ? <ul className="panel-list">{families.map(contact => <li key={contact.id}><div className="person-row"><span className="person-avatar">{(contact.user.profile?.displayName || "P").slice(0,1)}</span><div><strong>{contact.user.profile?.displayName || "Persona usuaria"}</strong><span>Te registró como {contact.relationship}</span></div></div>{contact.verifiedAt ? <span className="status-pill">Aceptado</span> : <InvitationActions contactId={contact.id} />}</li>)}</ul> : <div className="empty-state"><span>♡</span><h3>Aún no tienes invitaciones</h3><p>Pide a la persona usuaria que te invite con este mismo correo.</p></div>}</section><section className="info-panel"><span className="panel-kicker">CUANDO HAYA UNA ALERTA</span><h2>Tu papel en la red</h2><ol className="compact-steps"><li><span>1</span>Recibirás el aviso</li><li><span>2</span>Podrás confirmar que atenderás</li><li><span>3</span>Si es necesario, llamarás al 911</li></ol><p className="form-hint">Pulso no llama automáticamente a emergencias.</p></section></div>}
    {user.role === "USER" && <><section className="readiness-card"><div><span className="panel-kicker">PREPARACIÓN DEL HOGAR</span><h2>{contacts.some(contact => contact.verifiedAt) ? "Tu red ya empezó a tomar forma" : "Completa tu red de apoyo"}</h2><p>{contacts.some(contact => contact.verifiedAt) ? "Ya tienes al menos un vínculo confirmado. Puedes seguir agregando contactos antes de conectar el dispositivo." : "Invita a una persona de confianza. El vínculo quedará activo cuando verifique su correo y lo acepte."}</p></div><div className="readiness-ring"><strong>{contacts.some(contact => contact.verifiedAt) ? "2/3" : "1/3"}</strong><span>pasos listos</span></div></section><div className="panel-grid"><section className="info-panel"><div className="panel-heading"><div><span className="panel-kicker">PERSONAS DE CONFIANZA</span><h2>Tu red de apoyo</h2></div><span className="count-badge">{contacts.length}/5</span></div>{contacts.length ? <ul className="panel-list">{contacts.map(contact => <li key={contact.id}><div className="person-row"><span className="person-avatar">{contact.name.slice(0,1)}</span><div><strong>{contact.name}</strong><span>{contact.relationship} · {contact.email}</span></div></div><span className={contact.verifiedAt ? "status-pill" : "status-pill pending"}>{contact.verifiedAt ? "Aceptado" : "Pendiente"}</span></li>)}</ul> : <div className="empty-state compact"><span>＋</span><h3>Agrega tu primer contacto</h3><p>Usa el formulario para enviar una invitación segura.</p></div>}<ContactForm /></section><section className="info-panel"><span className="panel-kicker">SIGUIENTE PASO</span><h2>Prepara la demostración</h2><ul className="progress-list"><li className="done"><span>✓</span><div><strong>Cuenta verificada</strong><small>Correo y consentimiento registrados</small></div></li><li className={contacts.some(contact => contact.verifiedAt) ? "done" : "current"}><span>{contacts.some(contact => contact.verifiedAt) ? "✓" : "2"}</span><div><strong>Confirma tu red</strong><small>Al menos una persona debe aceptar</small></div></li><li><span>3</span><div><strong>Vincula el botón</strong><small>Disponible en la etapa ESP32</small></div></li></ul><Link className="button button-outline full-button" href="/demo">Probar simulador →</Link></section></div></>}
  </div></main></>;
}
